src/Apps/FluffyBunny.Admin/Pages/Tenant/AddApiResource.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Duende.IdentityServer.EntityFramework.Entities;
using FluffyBunny.Admin.Services;
using FluffyBunny.IdentityServer.EntityFramework.Storage.Entities;
using FluffyBunny.IdentityServer.EntityFramework.Storage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FluffyBunny.Admin.Pages.Tenant
{
    public class AddApiResourceModel : PageModel
    {
        private IAdminServices _adminServices;
        private ISessionTenantAccessor _sessionTenantAccessor;
        private ILogger<AddApiResourceModel> _logger;

        public AddApiResourceModel(
            IAdminServices adminServices,
            ISessionTenantAccessor sessionTenantAccessor,
            ILogger<AddApiResourceModel> logger)
        {
            _adminServices = adminServices;
            _sessionTenantAccessor = sessionTenantAccessor;
            _logger = logger;
        }
        [BindProperty]
        public string TenantId { get; set; }

        public class InputModel
        {
            [Required]
            public bool Enabled { get; set; }
            [Required]
            public string Name { get; set; }  // service name
            [Required]
            public string Description { get; set; }
        }
        [BindProperty]
        public InputModel Input { get; set; }
        public async Task OnGetAsync()
        {
            TenantId = _sessionTenantAccessor.TenantId;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                var entity = new ApiResource()
                {
                    Name = Input.Name,
                    Description = Input.Description,
                    
                    Enabled = Input.Enabled
                };
                await _adminServices.UpsertApiResourceAsync(TenantId, entity);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }
            return RedirectToPage("./ManageApiResources");
        }
    }
}

src/Apps/FluffyBunny.Admin/Pages/Tenant/AddApiResourceSecret.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Duende.IdentityServer;
using Duende.IdentityServer.EntityFramework.Entities;
using Duende.IdentityServer.Models;
using FluffyBunny.Admin.Model;
using FluffyBunny.Admin.Services;
using FluffyBunny.IdentityServer.EntityFramework.Storage.Services;
using FluffyBunny4.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FluffyBunny.Admin.Pages.Tenant
{
    public class AddApiResourceSecretModel : PageModel
    {
        private IAdminServices _adminServices;
        private IPasswordGenerator _passwordGenerator;
        private ISessionTenantAccessor _sessionTenantAccessor;
        private ILogger<AddApiResourceSecretModel> _logger;

        public AddApiResourceSecretModel(
            IAdminServices adminServices,
            IPasswordGenerator passwordGenerator,
            ISessionTenantAccessor sessionTenantAccessor,
            ILogger<AddApiResourceSecretModel> logger)
        {
            _adminServices = adminServices;
            _passwordGenerator = passwordGenerator;
            _sessionTenantAccessor = sessionTenantAccessor;
            _logger = logger;
        }

        [BindProperty]
        public string TenantId { get; set; }
        [BindProperty]
        public int ApiResourceId { get; set; }
       

 
        [BindProperty]
        public SecretModel Input { get; set; }
        public async Task OnGetAsync(int id)
        {
            TenantId = _sessionTenantAccessor.TenantId;
            ApiResourceId = id;
           

            Input = new SecretModel
            {
                Value = _passwordGenerator.GeneratePassword(),
                SecretExpiration = "Never"
            };
        }
        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                DateTime expiration = DateTime.UtcNow;
                switch (Input.SecretExpiration)
                {
                    case SecretModel.ExpirationTypes.Never:
                        expiration = expiration.AddYears(100);
                        break;
                    case SecretModel.ExpirationTypes.ExpireIt:
                        expiration = expiration.AddYears(-100);
                        break;
                    case SecretModel.ExpirationTypes.OneYear:
                        expiration = expiration.AddYears(1);
                        break;
                }

                var secret = new ApiResourceSecret()
                {
                    Type = IdentityServerConstants.SecretTypes.SharedSecret,
                    Expiration = expiration,
                    Description = Input.Value.Mask(4, '*'),
                    Value = Input.Value.Sha256()
                };

 
                await _adminServices.UpsertApiResourceSecretAsync(TenantId,ApiResourceId, secret);

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }

            return RedirectToPage("./ManageApiResourceSecrets", new { id = ApiResourceId });
        }
    }
}

src/Apps/FluffyBunny.Admin/Pages/Tenant/AddExternalService.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using FluffyBunny.Admin.Services;
using FluffyBunny.IdentityServer.EntityFramework.Storage.Entities;
using FluffyBunny.IdentityServer.EntityFramework.Storage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FluffyBunny.Admin.Pages.Tenant
{
    public class AddExternalServiceModel : PageModel
    {
        private IAdminServices _adminServices;
        private ISessionTenantAccessor _sessionTenantAccessor;
        private ILogger<AddExternalServiceModel> _logger;

        public AddExternalServiceModel(
            IAdminServices adminServices,
            ISessionTenantAccessor sessionTenantAccessor,
            ILogger<AddExternalServiceModel> logger)
        {
            _adminServices = adminServices;
            _sessionTenantAccessor = sessionTenantAccessor;
            _logger = logger;
        }
        [BindProperty]
        public string TenantId { get; set; }

        public class InputModel
        {
            public int Id { get; set; }
            public string Name { get; set; }  // service name
            [Required]
            public string Description { get; set; }
            [Required]
            public string Authority { get; set; }
            [Required]
            public bool Enabled { get; set; }
        }
        [BindProperty]
        public InputModel Input { get; set; }
        public async Task OnGetAsync()
        {
            TenantId = _sessionTenantAccessor.TenantId;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                var entity = new ExternalService
                {
                    Name = Input.Name,
                    Description = Input.Description,
                    Authority = Input.Authority,
                    Enabled = Input.Enabled
                };
                await _adminServices.UpsertExternalServiceAsync(TenantId, entity);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }
            return RedirectToPage("./ManageExternalServices");
        }
    }
}

src/Apps/FluffyBunny.Admin/Pages/Tenant/ApiResources/AddApiResource.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Duende.IdentityServer.EntityFramework.Entities;
using FluffyBunny.Admin.Services;
using FluffyBunny.IdentityServer.EntityFramework.Storage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FluffyBunny.Admin.Pages.Tenant.ApiResources
{
    public class AddApiResourceModel : PageModel
    {
        private IAdminServices _adminServices;
        private ISessionTenantAccessor _sessionTenantAccessor;
        private ILogger<AddApiResourceModel> _logger;

        public AddApiResourceModel(
            IAdminServices adminServices,
            ISessionTenantAccessor sessionTenantAccessor,
            ILogger<AddApiResourceModel> logger)
        {
            _adminServices = adminServices;
            _sessionTenantAccessor = sessionTenantAccessor;
            _logger = logger;
        }
        [BindProperty]
        public string TenantId { get; set; }

        public class InputModel
        {
            [Required]
            public bool Enabled { get; set; }
            [Required]
            public string Name { get; set; }  // service name
            [Required]
            public string Description { get; set; }
        }
        [BindProperty]
        public InputModel Input { get; set; }
        public async Task OnGetAsync()
        {
            TenantId = _sessionTenantAccessor.TenantId;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                var entity = new ApiResource()
                {
                    Name = Input.Name,
                    Description = Input.Description,
                    
                    Enabled = Input.Enabled
                };
                await _adminServices.UpsertApiResourceAsync(TenantId, entity);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }
            return RedirectToPage("./ManageApiResources");
        }
    }
}

src/Apps/FluffyBunny.Admin/Pages/Tenant/ApiResources/DeleteApiResource.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Duende.IdentityServer.EntityFramework.Entities;
using FluffyBunny.Admin.Services;
using FluffyBunny.IdentityServer.EntityFramework.Storage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FluffyBunny.Admin.Pages.Tenant.ApiResources
{
    public class DeleteApiResourceModel : PageModel
    {
        private IAdminServices _adminServices;
        private ISessionTenantAccessor _sessionTenantAccessor;
        private ILogger<DeleteApiResourceModel> _logger;

        public DeleteApiResourceModel(
            IAdminServices adminServices,
            ISessionTenantAccessor sessionTenantAccessor,
            ILogger<DeleteApiResourceModel> logger)
        {
            _adminServices = adminServices;
            _sessionTenantAccessor = sessionTenantAccessor;
            _logger = logger;
        }
        [BindProperty]
        public string TenantId { get; set; }
        public ApiResource Entity { get; private set; }
        public class InputModel
        {
            [Required]
            public int Id { get; set; }
        }
        [BindProperty]
        public InputModel Input { get; set; }
        public async Task OnGetAsync(int id)
        {
            TenantId = _sessionTenantAccessor.TenantId;
            Entity = await _adminServices.GetApiResourceByIdAsync(TenantId, id);
            Input = new InputModel()
            {
                Id = Entity.Id
            };
        }
        public async Task<IActionResult> OnPostAsync(string submit)
        {
            try
            {
                if (string.Compare(submit, "delete", true) == 0)
                {
                    await _adminServices.DeleteApiResourceByIdAsync(TenantId, Input.Id);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }

            return RedirectToPage("./ManageApiResources");
        }
    }
}

src/Apps/FluffyBunny.Admin/Pages/Tenant/ManageApiResources.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Duende.IdentityServer.EntityFramework.Entities;
using FluffyBunny.Admin.Services;
using FluffyBunny.IdentityServer.EntityFramework.Storage;
using FluffyBunny.IdentityServer.EntityFramework.Storage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace FluffyBunny.Admin.Pages.Tenant
{
    public class ManageApiResourcesModel : PageModel
    {
        private IAdminServices _adminServices;
        private ISessionTenantAccessor _sessionTenantAccessor;
        private IPagingHelper _pagingHelper;
        private ILogger<ManageApiResourcesModel> _logger;

        public ManageApiResourcesModel(
            IAdminServices adminServices,
            ISessionTenantAccessor sessionTenantAccessor,
            IPagingHelper pagingHelper,
            ILogger<ManageApiResourcesModel> logger)
        {
            _adminServices = adminServices;
            _sessionTenantAccessor = sessionTenantAccessor;
            _pagingHelper = pagingHelper;
            _logger = logger;
        }

        [BindProperty]
        public string TenantId { get; set; }

        public List<SelectListItem> PageSizeOptions { get; private set; }

        [ViewData]
        public ApiResourcesSortType NameSortType { get; set; }
        public PaginatedList<ApiResource> PagedEntities { get; private set; }
        [ViewData]
        public ApiResourcesSortType EnabledSortType { get; set; }
        [ViewData]
        public ApiResourcesSortType CurrentSortType { get; set; }

        [ViewData]
        public int PageSize { get; set; }

        [BindProperty]
        public int SelectedPageSize { get; set; }

        public async Task OnGetAsync(ApiResourcesSortType sortOrder, int? pageNumber, int? pageSize)
        {
            TenantId = _sessionTenantAccessor.TenantId;
            PageSize = _pagingHelper.ValidatePageSize(pageSize);
            PageSizeOptions = _pagingHelper.GetPagingSizeOptions();
            SelectedPageSize = PageSize;

            switch (sortOrder)
            {

                case ApiResourcesSortType.EnabledAsc:
                    PagedEntities =
                        await _adminServices.PageApiResourcesAsync(
                            TenantId,
                            (int)(pageNumber ?? 1),
                            PageSize,
                            ApiResourcesSortType.EnabledAsc);
                    EnabledSortType = ApiResourcesSortType.EnabledDesc;
                    break;
                case ApiResourcesSortType.EnabledDesc:
                    PagedEntities =
                        await _adminServices.PageApiResourcesAsync(
                            TenantId,
                            (int)(pageNumber ?? 1),
                            PageSize,
                            ApiResourcesSortType.EnabledDesc);
                    EnabledSortType = ApiResourcesSortType.EnabledAsc;
                    break;
                case ApiResourcesSortType.NameDesc:
                    PagedEntities =
                        await _adminServices.PageApiResourcesAsync(
                            TenantId,
                            (int)(pageNumber ?? 1),
                            PageSize,
                            ApiResourcesSortType.NameDesc);
                    NameSortType = ApiResourcesSortType.NameAsc;
                    EnabledSortType = ApiResourcesSortType.EnabledDesc;
                    break;
                case ApiResourcesSortType.NameAsc:
                default:
                    PagedEntities =
                        await _adminServices.PageApiResourcesAsync(
                            TenantId,
                            (int)(pageNumber ?? 1),
                            PageSize,
                            ApiResourcesSortType.NameAsc);
                    NameSortType = ApiResourcesSortType.NameDesc;
                    EnabledSortType = ApiResourcesSortType.EnabledDesc;

                    break;
            }

            CurrentSortType = sortOrder;
        }
        public async Task<IActionResult> OnPostPageSizeAsync()
        {
            return RedirectToPage(new { sortOrder = CurrentSortType, pageNumber = 1, pageSize = SelectedPageSize });
        }
    }
}

src/Apps/FluffyBunny.Admin/Pages/Tenant/AddApiResource.cshtml
@page
@model FluffyBunny.Admin.Pages.Tenant.AddApiResourceModel
@{
    ViewData["Title"] = "Add Api Resource";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-area="" asp-page="/Tenants/Index">Tenants</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-page="./Index">@Model.TenantId</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-page="./ManageApiResources">Api Resources</a></li>

        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>

<form method="post">
    <div class="card">
        <div class="card-header">
            Add Api Resource
        </div>
        <input hidden asp-for="TenantId" class="form-control" />
        <div id="cardBodyId">

            <div class="card-body">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <table class="table">

                        <tbody>

                            <tr>

                                <td class="w-50">
                                </td>
                                <td class="w-50">
                                    <input asp-for="Input.Enabled" />
                                    <label>Enabled</label>
                                </td>
                            </tr>
                            <tr>
                                <td class="w-50">
                                    @nameof(Model.Input.Name)
                                </td>
                                <td class="w-50">
                                    <input asp-for="Input.Name" class="form-control" />
                                    <span asp-validation-for="Input.Name" class="text-danger"></span>
                                </td>
                            </tr>
                            <tr>
                                <td class="w-50">
                                    @nameof(Model.Input.Description)
                                </td>
                                <td class="w-50">
                                    <input asp-for="Input.Description" class="form-control" />
                                    <span asp-validation-for="Input.Description" class="text-danger"></span>
                                </td>
                            </tr>
                           
                        <tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

src/Apps/FluffyBunny.Admin/Pages/Tenant/ManageApiResources.cshtml
@page
@model FluffyBunny.Admin.Pages.Tenant.ManageApiResourcesModel
@{
    ViewData["Title"] = "Api Resources";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-area="" asp-page="/Tenants/Index">Tenants</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-page="./Index">@Model.TenantId</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>


@{
    var prevDisabled = !Model.PagedEntities.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.PagedEntities.HasNextPage ? "disabled" : "";
}

<div class="card">
    <div class="card-header text-muted">
        <a class="btn btn-sm btn-primary" asp-page="./AddApiResource">Add Api Resource</a>
    </div>
    @if (Model.PagedEntities.Any())
    {
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th colspan="1">
                            <a asp-action="Index"
                               asp-route-sortOrder="@Model.EnabledSortType"
                               asp-route-pageSize="@Model.PageSize">Status</a>
                        </th>
                        <th colspan="1">
                            <a asp-action="Index"
                               asp-route-sortOrder="@Model.NameSortType"
                               asp-route-pageSize="@Model.PageSize">Service</a>
                        </th>

                        <th colspan="1">Description</th>
                       
                        <th colspan="1"></th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0;i<Model.PagedEntities.Count;i++)
                    {
                        <tr>

                            <td class="w-50">
                                <input disabled asp-for="PagedEntities[i].Enabled" />
                                <label>Enabled</label>
                            </td>
                            <td class="w-50">
                                @Model.PagedEntities[i].Name
                            </td>
                            <td class="w-50">
                                @Model.PagedEntities[i].Description
                            </td>
                          
                            <td class="w-50">
                                <div class="btn-group ">
                                    <a 
                                       
                                       class="btn btn-primary btn-sm active "
                                       role="button" aria-pressed="true"
                                       asp-page="./ManageApiResourceSecrets"
                                       asp-route-id="@Model.PagedEntities[i].Id">Secrets</a>
                                    <a 
                                        style="border-left-color: white;"
                                       class="btn btn-primary btn-sm active "
                                       role="button" aria-pressed="true"
                                       asp-page="./EditApiResource"
                                       asp-route-id="@Model.PagedEntities[i].Id">Edit</a>
                                    <a style="border-left-color: white;"
                                       class="btn btn-primary btn-sm active " role="button" aria-pressed="true"
                                       asp-page="./DeleteApiResource"
                                       asp-route-id="@Model.PagedEntities[i].Id">Delete</a>
                                </div>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div class="card-footer text-muted container-fluid">
            <div class="d-flex bd-highlight mb-3">
                <div class="p-2 bd-highlight">

                    <a class="btn btn-sm btn-primary @prevDisabled" asp-page="/Tenant/ManageApiResources"
                       asp-route-sortOrder="@Model.CurrentSortType"
                       asp-route-pageNumber="@(Model.PagedEntities.PageIndex - 1)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]">Previous</a>

                    <a class="btn btn-sm btn-primary @nextDisabled" asp-page="/Tenant/ManageApiResources"
                       asp-route-sortOrder="@Model.CurrentSortType"
                       asp-route-pageNumber="@(Model.PagedEntities.PageIndex + 1)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]">Next</a>
                </div>

                <div class="ml-auto p-2 bd-highlight">
                    <form class="form-inline"
                          asp-page-handler="pageSize"
                          method="post">
                        <select onchange="this.form.submit();"
                                asp-for="SelectedPageSize"
                                asp-items="Model.PageSizeOptions" class="custom-select">
                        </select>
                    </form>
                </div>
            </div>
        </div>
    }

</div>

src/Apps/FluffyBunny.Admin/Pages/Tenant/ManageExternalServices.cshtml
@page
@model FluffyBunny.Admin.Pages.Tenant.ManageExternalServicesModel
@{
    ViewData["Title"] = "External Services";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-area="" asp-page="/Tenants/Index">Tenants</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-page="./Index">@Model.TenantId</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>

@{
    var prevDisabled = !Model.PagedEntities.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.PagedEntities.HasNextPage ? "disabled" : "";
}

<div class="card">
    <div class="card-header text-muted">
        <a class="btn btn-sm btn-primary" asp-page="./AddExternalService">Add External Service</a>
    </div>
    @if (Model.PagedEntities.Any())
    {
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th colspan="1">
                            <a asp-action="Index"
                               asp-route-sortOrder="@Model.EnabledSortType"
                               asp-route-pageSize="@Model.PageSize">Enabled</a>
                        </th>
                        <th colspan="1">
                            <a asp-action="Index"
                               asp-route-sortOrder="@Model.NameSortType"
                               asp-route-pageSize="@Model.PageSize">Service</a>
                        </th>

                        <th colspan="1">Description</th>
                        <th colspan="1">Authority</th>
                        <th colspan="1"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var entity in Model.PagedEntities)
                    {
                        <tr>

                            <td >
                                @entity.Enabled
                            </td>
                            <td >
                                @entity.Name
                            </td>
                            <td >
                                @entity.Description
                            </td>
                            <td >
                                @entity.Authority
                            </td>
                            <td >
                                <div class="btn-group " >
                                    <a 
                                        style="border-right-color: white;"
                                        class="btn btn-primary btn-sm active " 
                                        role="button" aria-pressed="true"
                                        asp-page="./EditExternalService"
                                        asp-route-id="@entity.Id">Edit</a>
                                    <a    style="border-left-color: white;"
                                       class="btn btn-primary btn-sm active " role="button" aria-pressed="true"
                                       asp-page="./DeleteExternalService"
                                       asp-route-id="@entity.Id">Delete</a>
                                </div>
                               
                            </td>
                        </tr>
                    }
                   
                </tbody>
            </table>
        </div>

        <div class="card-footer text-muted container-fluid">
            <div class="d-flex bd-highlight mb-3">
                <div class="p-2 bd-highlight">

                    <a class="btn btn-sm btn-primary @prevDisabled" asp-page="./ManageExternalServices"
                       asp-route-sortOrder="@Model.CurrentSortType"
                       asp-route-pageNumber="@(Model.PagedEntities.PageIndex - 1)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]">Previous</a>

                    <a class="btn btn-sm btn-primary @nextDisabled" asp-page="./ManageExternalServices"
                       asp-route-sortOrder="@Model.CurrentSortType"
                       asp-route-pageNumber="@(Model.PagedEntities.PageIndex + 1)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]">Next</a>
                </div>

                <div class="ml-auto p-2 bd-highlight">
                    <form class="form-inline"
                          asp-page-handler="pageSize"
                          method="post">
                        <select onchange="this.form.submit();"
                                asp-for="SelectedPageSize"
                                asp-items="Model.PageSizeOptions" class="custom-select">
                        </select>
                    </form>
                </div>
            </div>
        </div>
    }

</div>
 